### ISSUE TITLE
Elaborar Rich Picture (individual)

### ISSUE THREAD

**Issue by gleal17** [Requisitos2-2019/Waze#2]
## Descrição da Issue

Cada integrante deve fazer um RIch Picture do app escolhido (Waze).

Tasks:

- [x] @MoacirMSJ 
- [x] @jpcirqueira
- [x] @MatheusEstanislau 

Obs.: Marquem na issue o check box ao terminar.

**Comment by jpcirqueira** [comment]
apresentação:
- apresentar equipe (Guilherme)
- falar sobre o waze (Guilherme)
- recursos humanos (Renan)
- planejamento (Lucas alexandre)
- richpicture (Cristo)
- metodoligia (Moacir)
- plataformas (Moacir)
- apresentar pages(João Pedro)
- link do pages(João Pedro)

**Comment by jpcirqueira** [comment]
@MatheusEstanislau ajustar a issue e colocar no quadro certo.

**Comment by gleal17** [comment]
Rich picture escolhido (@MatheusEstanislau),
