### ISSUE TITLE
Criar slides para apresentação

### ISSUE THREAD

**Issue by MatheusEstanislau** [Requisitos2-2019/Waze#6]
# Criar slides para apresentação

## Descrição da Issue
Montar slides para a primeira apresentação

### Tarefas:
- [x] Informação da equipe e aplicativo utilizado
- [x] Apresentação dos integrantes
- [x] Planilha contento os pontos de controle
- [x] Planilha contendo os horários compatíveis dos membros
- [x] Apresentação do RichPicture
- [x] metodologias e plataformas que serão utilizadas
- [x] repositório
- [x] pages 

## Assignees
@MoacirMSJ @jpcirqueira @lucasA27 @MatheusEstanislau @RCristyan @gleal17

**Comment by jpcirqueira** [comment]
apresentação:
- apresentar equipe (Guilherme)
- falar sobre o waze (Guilherme)
- recursos humanos (Renan)
- planejamento (Lucas alexandre)
- richpicture (Cristo)
- metodoligia (Moacir)
- plataformas (Moacir)
- apresentar pages(João Pedro)
- link do pages(João Pedro)
